Runtime error fix. (#408)
Helper functions are now being added on creation of the template instead on render.

This was cauing `Exception in template helper: TypeError: Template.instance(...).loadHangouts is not a function` to occur.